### ISSUE TITLE
"Error: Could not resolve" invalid path

### ISSUE THREAD

**Issue by TheBosZ** [calvinmetcalf/rollup-plugin-node-globals#4] opened 2016-09-21 15:53 UTC
When I include this plugin (I'm trying to get the AWS SDK working), I get an error as follows. It looks like my paths are losing backslash (\\). I'm on Windows 10.

```
C:\Projects\cloud-iris-web-frontend>.\node_modules\.bin\rollup -c
Could not resolve 'C:Projectscloud-iris-web-frontend
ode_modulesprocess-esrowser.js' from C:\Projects\cloud-iris-web-frontend\node_modules\react\lib\checkReactTypeSpec.js
Error: Could not resolve 'C:Projectscloud-iris-web-frontend
ode_modulesprocess-esrowser.js' from C:\Projects\cloud-iris-web-frontend\node_modules\react\lib\checkReactTypeSpec.js
    at Error (native)
    at C:\Projects\cloud-iris-web-frontend\node_modules\rollup-plugin-node-resolve\dist\rollup-plugin-node-resolve.cjs.js:78:21
    at C:\Projects\cloud-iris-web-frontend\node_modules\browser-resolve\index.js:265:24
    at C:\Projects\cloud-iris-web-frontend\node_modules\resolve\lib\async.js:46:14
    at process (C:\Projects\cloud-iris-web-frontend\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Projects\cloud-iris-web-frontend\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Projects\cloud-iris-web-frontend\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Projects\cloud-iris-web-frontend\node_modules\resolve\lib\async.js:92:31)
    at C:\Projects\cloud-iris-web-frontend\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
```

My rollup.config.js is:

```
import typescript from 'rollup-plugin-typescript';
import babel   from 'rollup-plugin-babel'
import replace from 'rollup-plugin-replace'
import uglify from 'rollup-plugin-uglify';
import sass from 'rollup-plugin-sass';
import commonjs from 'rollup-plugin-commonjs';
import resolve from 'rollup-plugin-node-resolve';
import json from 'rollup-plugin-json';
import builtins from 'rollup-plugin-node-builtins';
import globals from 'rollup-plugin-node-globals';

export default {
	entry: './src/index.tsx',
	dest: './dist/app.min.js',
	format: 'iife',
	sourceMap: './dist/app.min.js.map',
	moduleName: 'MyBundle',
	plugins: [
		builtins(),
		sass({
			insert: true,
			options: {
				outputStyle: 'compressed'
			}
		}),
		replace({
			'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development')
		}),
		typescript(),

		resolve({
			jsnext: true,
			main: true,
			browser: true,
			preferBuiltins: true
		}),

		commonjs({
			ignoreGlobal: true,
			namedExports: {
				'react': [
					'PropTypes',
					'createElement',
					'cloneElement',
					'Component'
				],
				'node_modules/react-dom/index.js': [
					'render'
				]
			},
			exclude: [
			]
		}),

		babel({
			exclude: 'node_modules/**',
			compact: false
		}),
		globals(),
		json(),

		(process.env.NODE_ENV === 'production' && uglify())
	]
}
```

**Comment by calvinmetcalf** [comment] 2016-09-21 16:26
try putting globals before resolve, this may be a weird interaction between the 2

**Comment by TheBosZ** [comment] 2016-09-21 16:40
Ah. I had tried putting it in multiple different places, and I kept getting different errors.

With it above resolve I get this one:

```
Error parsing C:\Projects\cloud-iris-web-frontend\node_modules\react\lib\checkReactTypeSpec.js: 'import' and 'export' may only appear at the top level (16:0) in C:\Projects\cloud-iris-web-frontend\node_modules\react\lib\checkReactTypeSpec.js
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
```

**Comment by calvinmetcalf** [comment] 2016-09-21 16:45
ok commonjs needs to before globals so try putting resolve at the end, that will at least fix the different error (which is because globals inserts `import foo from 'bar'` statments but commonjs wraps in a function)

**Comment by calvinmetcalf** [comment] 2016-09-21 16:47
actually if you could from inside your directory open a node console (by typing node) and type `require.resolve('process-es6')` I wonder if something weird is happening on windows

**Comment by TheBosZ** [comment] 2016-09-21 16:50
I'm back to the original "invalid path" error with the order being:
```
builtins()
sass()
replace()
typescript()
commonjs()
globals()
resolve()
babel()
json()
```
node
> require.resolve('process-es6');
'C:\\Projects\\cloud-iris-web-frontend\\node_modules\\process-es6\\browser.js'
>

**Comment by calvinmetcalf** [comment] 2016-09-21 17:02
I think this is actually a bug in the resolve plugin, which is doing `importee.split( /[\/\\]/)` where importee is `'C:\Projects\cloud-iris-web-frontend\node_modules\process-es6\browser.js'` which bizarrely results in

```js
[ 'C:Projectscloud-iris-web-frontend\node_modulesprocess-es6\browser.js' ]
```
let me look into this

**Comment by calvinmetcalf** [comment] 2016-09-21 17:08
nm simply typing 'C:\Projects\cloud-iris-web-frontend\node_modules\process-es6\browser.js' in the console results in 'C:Projectscloud-iris-web-frontend\node_modulesprocess-es6\browser.js'

**Comment by TheBosZ** [comment] 2016-09-21 17:11
Stupid Windows and backslashes.

**Comment by calvinmetcalf** [comment] 2016-09-21 17:17
I'm not on windows, but it seems that somewhere the results of require.resolve are being treated as ''C:\Projects\cloud-iris-web-frontend\node_modules\process-es6\browser.js' instead of 'C:\\Projects\\cloud-iris-web-frontend\\node_modules\\process-es6\\browser.js'

**Comment by TheBosZ** [comment] 2016-09-21 17:19
Should this bug be moved over to the resolve plugin?

**Comment by calvinmetcalf** [comment] 2016-09-21 17:20
no I spoke to soon there, what version of node ?

**Comment by TheBosZ** [comment] 2016-09-21 17:21
C:\Projects\cloud-iris-web-frontend>node -v
v6.5.0

**Comment by calvinmetcalf** [comment] 2016-09-21 17:37
ok just booted up a vm I had laying around

```shell
> require.resolve('process-es6')
'C:\\Users\\IEUser\\projects\\node_modules\\process-es6\\browser.js'
```
are you on the ubuntu subshell per chance ?

**Comment by TheBosZ** [comment] 2016-09-21 17:38
Nope, this is Windows 10 "node.js command prompt"

**Comment by TheBosZ** [comment] 2016-09-21 17:40
Oops, I just noticed that my paste into here didn't properly escape the slashes from me running require.resolve.

I get the same output as you:
```
C:\Projects\cloud-iris-web-frontend>node
> require.resolve('process-es6');
'C:\\Projects\\cloud-iris-web-frontend\\node_modules\\process-es6\\browser.js'
>
```

**Comment by calvinmetcalf** [comment] 2016-09-21 18:32
ok managed to reproduce it, something having to do with the strings being deescaped somehow, I think I know a fix

**Comment by calvinmetcalf** [comment] 2016-09-22 13:12
ok should be fixed in 1.0.9

**Closed by calvinmetcalf** 2016-09-22 13:12 UTC

**Comment by TheBosZ** [comment] 2016-09-22 15:42
I've updated the plugin and now I'm getting:

```
Illegal reassignment to import 'process'
Error: Illegal reassignment to import 'process'
    at error (C:\Projects\cloud-iris-web-frontend\node_modules\rollup\src\utils\error.js:2:14)
    at disallowIllegalReassignment (C:\Projects\cloud-iris-web-frontend\node_modules\rollup\src\ast\nodes\shared\disallowIllegalReassignment.js:20:4)
    at AssignmentExpression.bind (C:\Projects\cloud-iris-web-frontend\node_modules\rollup\src\ast\nodes\AssignmentExpression.js:12:3)
    at C:\Projects\cloud-iris-web-frontend\node_modules\rollup\src\ast\Node.js:6:34
    at ExpressionStatement.eachChild (C:\Projects\cloud-iris-web-frontend\node_modules\rollup\src\ast\Node.js:21:5)
    at ExpressionStatement.bind (C:\Projects\cloud-iris-web-frontend\node_modules\rollup\src\ast\Node.js:6:8)
    at BlockStatement.bind (C:\Projects\cloud-iris-web-frontend\node_modules\rollup\src\ast\nodes\BlockStatement.js:8:9)
    at C:\Projects\cloud-iris-web-frontend\node_modules\rollup\src\ast\Node.js:6:34
    at IfStatement.eachChild (C:\Projects\cloud-iris-web-frontend\node_modules\rollup\src\ast\Node.js:21:5)
    at IfStatement.bind (C:\Projects\cloud-iris-web-frontend\node_modules\rollup\src\ast\Node.js:6:8)
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
```

Is this a different error?

**Comment by calvinmetcalf** [comment] 2016-09-22 17:22
yes, but one that will be liekly easy for me to debug from a mac

**Comment by calvinmetcalf** [comment] 2016-09-22 17:35
yeah open up a new one this is likely going to depend on what libraries you are using

**Comment by TheBosZ** [comment] 2016-09-22 17:58
Thanks for your awesome help!

I'll see if I can get a narrow use case and open another issue.

FYI I'm trying to use the AWS SDK.
